### ISSUE TITLE
Diagram does not appear

### ISSUE THREAD

**Issue by xephon2** [townsen/gliffy#1]
Only "Array" appears. Mediawiki 1.15.5 on Ubuntu VM with Gliffy Trial. Link to diagram works.

![1](https://f.cloud.github.com/assets/3266567/873311/a4acd104-f874-11e2-9385-ff1bccfb7ebc.png)
![2](https://f.cloud.github.com/assets/3266567/873312/a58a42b4-f874-11e2-9f07-c99a017f7f6e.png)

**Comment by chazbot7** [comment]
@xephon2 you need to allow external images in your LocalSettings.php file:

https://www.mediawiki.org/wiki/Manual:$wgAllowExternalImages

**Comment by xephon2** [comment]
OK, thanks.
